name: Get Link

on:
  workflow_dispatch:

  schedule:
    - cron: 0/5 * * * *

  repository_dispatch:
    types:
      - link

  # push:
  #   branches:
  #     - main

jobs:
  pre:
    name: Pre
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      sites: ${{ steps.sites.outputs.value }}
    steps:
      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Check list website
        id: sites
        run: echo "value=$(node src/functions/websites.js)" >> $GITHUB_OUTPUT

      - name: Echo value
        run: echo "${{ steps.sites.outputs.value }}"

  run:
    name: Run ${{ matrix.site_name}}
    runs-on: ubuntu-latest
    needs: [pre]
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        include: ${{ fromJson(needs.pre.outputs.sites) }}
    env:
      SITE_URL: ${{ matrix.site_url }}

    steps:
      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Run get link
        run: npm run get:url
        env:
          SITE_CODE: ${{ matrix.code }}

      - name: Generate artifact file
        id: file-name
        run: |
          FILE_NAME=$(echo $(date +'ART%y%m%d')$(openssl rand -hex 3) | perl -ne 'print uc')
          cp .temp/data.json $FILE_NAME.json
          echo "value=$FILE_NAME" >> $GITHUB_OUTPUT

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.file-name.outputs.value }}
          path: ${{ steps.file-name.outputs.value }}.json
          if-no-files-found: warn

  after:
    name: After
    needs: [run]
    runs-on: ubuntu-latest
    steps:
      - name: Download from artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Generate result file
        id: get-link
        run: |
          flattened_json=$(jq -sc 'map(.[])' *)
          cleaned_json=$(echo "$flattened_json" | sed 's/^[ \t]*//' | tr -d '\n\r')
          echo "value=$cleaned_json" >> $GITHUB_OUTPUT

      - name: Checkout crawl
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/nodejs-clutter
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.GH_PAT }}
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Checkout links data
        uses: actions/checkout@v4
        with:
          repository: ClutterNews/kh-data
          path: src/databases/data
          token: ${{ secrets.GH_PAT }}

      - name: Pull again
        working-directory: src/databases/data
        run: git pull origin main

      - name: Store links
        run: |
          echo '${{ steps.get-link.outputs.value }}' > ./.temp/articles.json
          node src/functions/insertArticles.js

      - name: Check git data changes
        id: is_data_change
        working-directory: src/databases/data
        continue-on-error: true
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "value=true" >> $GITHUB_OUTPUT
          else
            echo "value=false" >> $GITHUB_OUTPUT
          fi

      - name: Push
        working-directory: src/databases/data
        if: steps.is_data_change.outputs.value == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m ':white_check_mark: Get Links'
          git push origin main -f

      - name: Trgger Meta
        if: steps.is_data_change.outputs.value == 'true'
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.github.com/repos/cltnp/ppap/dispatches"
          method: "POST"
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.GH_PAT }}", "X-GitHub-Api-Version": "2022-11-28"}'
          data: '{"event_type": "meta"}'
